# fly.toml app configuration file generated for fem-multi-step-form-frontend on 2024-02-18T16:24:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fem-multi-step-form-frontend'
primary_region = 'yyz'

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
